### ISSUE TITLE
master or main branche

### ISSUE THREAD

**Issue by schlagi123** [DeusExtimus/ABCalendar#18]
Hi,

you have a master and a main branch, did you use both?
I think, you don't need the master branch.

**Comment by DeusExtimus** [comment]
Deleted the master branch, because the new convention says that the main branch should be the origin branch. Thanks for the hint

**Comment by DeusExtimus** [comment]
Deleted the master branch, because the new convention says that the main branch should be the origin branch. Thanks for the hint

**Comment by DeusExtimus** [comment]
Deleted the master branch, because the new convention says that the main branch should be the origin branch. Thanks for the hint
